name: Nightly Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Debug
      run: MSBuild MinecraftConsoles.sln /t:Build /p:Configuration=Debug /p:Platform=Windows64 /m

    - name: Show build output
      run: dir x64\Debug /s

    - name: Zip build
      run: 7z a LCEWindows64.zip ./x64/Debug/

    - name: Publish nightly
      uses: andelf/nightly-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly
        name: Nightly Release
        files: LCEWindows64.zip
