name: Nightly Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Debug
      run: MSBuild MinecraftConsoles.sln /t:Build /p:Configuration=Debug /p:Platform=Windows64 /m

    - name: Inspect Debug folder
      run: |
           Get-ChildItem -Path "x64/Debug" -Recurse
           $size = (Get-ChildItem -Path "x64/Debug" -Recurse | Measure-Object -Property Length -Sum).Sum
           Write-Output "Debug folder size: $($size / 1MB) MB"
           
    - name: Zip build
      run: 7z a LCEWindows64.zip ./x64/Debug/

    - name: Publish nightly
      uses: andelf/nightly-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly
        name: Nightly Release
        files: LCEWindows64.zip
